Repository eclipse-zenoh/zenoh-cpp, pull requests merged in 2024-12, with the labels that each got.

#298 fix: standalone archive following homebrew naming
  .github/workflows/release.yml
Labels: internal

#303 fix: prepare standalone archives for homebrew
  .github/workflows/release.yml
Labels: internal

#305 Fix homebrew publish
  .github/workflows/release.yml
Labels: internal

#306 fix: add ci status check
  .github/workflows/ci.yml
Labels: internal

#300 fix liveliness examples not being built for zenoh-pico if zenoh-c is disabled
  examples/CMakeLists.txt
Labels: bug

#318 Align examples with rust and fix argument parsing in examples
  examples/getargs.h
  examples/getargs.hxx
  examples/universal/z_delete.cxx
  examples/universal/z_get.cxx
  examples/universal/z_get_attachment.cxx
  examples/universal/z_get_channel.cxx
  examples/universal/z_get_channel_non_blocking.cxx
  examples/universal/z_get_liveliness.cxx
  examples/universal/z_info.cxx
  examples/universal/z_liveliness.cxx
  examples/universal/z_ping.cxx
  examples/universal/z_pong.cxx
  examples/universal/z_pub.cxx
  examples/universal/z_pub_attachment.cxx
  examples/universal/z_pub_delete.cxx
  examples/universal/z_pub_thr.cxx
  examples/universal/z_put.cxx
  examples/universal/z_queryable.cxx
  examples/universal/z_queryable_attachment.cxx
  examples/universal/z_scout.cxx
  examples/universal/z_sub.cxx
  examples/universal/z_sub_attachment.cxx
  examples/universal/z_sub_liveliness.cxx
  examples/universal/z_sub_thr.cxx
  examples/zenohc/z_get_shm.cxx
  examples/zenohc/z_ping_shm.cxx
  examples/zenohc/z_pub_cache.cxx
  examples/zenohc/z_pub_shm.cxx
  examples/zenohc/z_pub_shm_thr.cxx
  examples/zenohc/z_querier.cxx
  examples/zenohc/z_query_sub.cxx
  examples/zenohc/z_queryable_shm.cxx
  examples/zenohc/z_sub_shm.cxx
  include/zenoh/api/keyexpr.hxx
Labels: bug

#323 fix cli argument parsing in examples
  examples/getargs.hxx
  examples/universal/z_pub_thr.cxx
Labels: enhancement, api sync

#330 fix: exclude internal from automatic changelog
  .github/release.yml
Labels: internal

#329 Add CI for checking markdown format.
  .github/workflows/ci.yml
  .markdownlint.yaml
  README.md
  docs/README.md
Labels: internal

#335 add support for transferring data ownership to Bytes via custom deleter
  include/zenoh/api/bytes.hxx
  tests/universal/bytes.cxx
Labels: enhancement

#337 add missing inlines to declare_publication_cache implementations
  include/zenoh/api/ext/publication_cache.hxx
Labels: bug, internal

#341 remove unneeded command from ci
  .github/workflows/ci.yml
Labels: internal

#342 Addes missing include to zshm
  include/zenoh/api/shm/buffer/zshm.hxx
Labels: bug

#349 fix: corrected the syntax of links in README.md
  README.md
Labels: documentation, internal

#354 Fix liveliness timeout type
  include/zenoh/api/session.hxx
Labels: bug, api sync
