Repository eclipse-zenoh/zenoh-cpp, pull requests merged in 2024-09, with the labels that each got.

#196 Support for the QNX 7.1.0 qcc compiler
  examples/universal/z_get.cxx
  examples/universal/z_get_attachment.cxx
  examples/universal/z_get_channel.cxx
  examples/universal/z_get_channel_non_blocking.cxx
  examples/universal/z_pub.cxx
  examples/universal/z_pub_attachment.cxx
  examples/universal/z_pub_thr.cxx
  examples/universal/z_put.cxx
  examples/universal/z_queryable.cxx
  examples/universal/z_queryable_attachment.cxx
  include/zenoh/api/bytes.hxx
  include/zenoh/api/closures.hxx
Labels: bug, release

#205 add missing reliability options for delete operation and reliability sample accessor
  include/zenoh/api/sample.hxx
  include/zenoh/api/session.hxx
Labels: release, api sync, internal

#207 mark unstable features in the docs
  include/zenoh/api/enums.hxx
  include/zenoh/api/hello.hxx
  include/zenoh/api/id.hxx
  include/zenoh/api/keyexpr.hxx
  include/zenoh/api/liveliness.hxx
  include/zenoh/api/publisher.hxx
  include/zenoh/api/query.hxx
  include/zenoh/api/reply.hxx
  include/zenoh/api/sample.hxx
  include/zenoh/api/session.hxx
  include/zenoh/api/shm/buffer/zshm.hxx
  include/zenoh/api/shm/buffer/zshmmut.hxx
  include/zenoh/api/shm/client/shm_client.hxx
  include/zenoh/api/shm/client/shm_segment.hxx
  include/zenoh/api/shm/client_storage/client_storage.hxx
  include/zenoh/api/shm/protocol_implementations/posix/posix_shm_client.hxx
  include/zenoh/api/shm/protocol_implementations/posix/posix_shm_provider.hxx
  include/zenoh/api/shm/provider/alloc_layout.hxx
  include/zenoh/api/shm/provider/chunk.hxx
  include/zenoh/api/shm/provider/shm_provider.hxx
  include/zenoh/api/shm/provider/types.hxx
  include/zenoh/api/source_info.hxx
  include/zenoh/api/timestamp.hxx
Labels: documentation

#208 move Reliability enum under unstable
  include/zenoh/api/enums.hxx
Labels: bug, documentation

#210 remove Config::client() and ::peer() methods
  include/zenoh/api/config.hxx
  tests/zenohc/config.cxx
Labels: api sync, internal

#212 liveliness history support
  include/zenoh/api/session.hxx
Labels: enhancement, api sync

#214 update docs regarding undefined behavior when using multiple Bytes::Writers
  include/zenoh/api/bytes.hxx
Labels: documentation, internal

#220 add slice iterator api for Bytes
  include/zenoh/api/bytes.hxx
Labels: enhancement, api sync

#222 SourceSn is uint32_t and not uint64_t
  include/zenoh/api/source_info.hxx
Labels: internal

#218 z_bytes example
  CMakeLists.txt
  examples/CMakeLists.txt
  examples/universal/proto/entity.proto
  examples/universal/z_bytes.cxx
Labels: enhancement, release

#236 chore: update release.yml for required labels
  .github/release.yml
Labels: internal
