Repository eclipse-zenoh/zenoh-cpp, pull requests merged in 2024-10, with the labels that each got.

#234 clarify readme regarding installation prerequisites
  README.md
Labels: documentation

#232 Do not re-define targets if find_package(zenohcxx) is called twice
  install/PackageConfig.cmake.in
Labels: bug

#240 support for peer mode in zenoh-pico examples
  examples/getargs.h
  examples/universal/z_delete.cxx
  examples/universal/z_get.cxx
  examples/universal/z_get_attachment.cxx
  examples/universal/z_get_channel.cxx
  examples/universal/z_get_channel_non_blocking.cxx
  examples/universal/z_info.cxx
  examples/universal/z_ping.cxx
  examples/universal/z_pong.cxx
  examples/universal/z_pub.cxx
  examples/universal/z_pub_attachment.cxx
  examples/universal/z_pub_delete.cxx
  examples/universal/z_pub_thr.cxx
  examples/universal/z_put.cxx
  examples/universal/z_queryable.cxx
  examples/universal/z_queryable_attachment.cxx
  examples/universal/z_scout.cxx
  examples/universal/z_sub.cxx
  examples/universal/z_sub_attachment.cxx
  examples/universal/z_sub_thr.cxx
  examples/zenohc/z_get_liveliness.cxx
  examples/zenohc/z_get_shm.cxx
  examples/zenohc/z_liveliness.cxx
  examples/zenohc/z_ping_shm.cxx
  examples/zenohc/z_pub_shm.cxx
  examples/zenohc/z_pub_shm_thr.cxx
  examples/zenohc/z_queryable_shm.cxx
  examples/zenohc/z_sub_liveliness.cxx
  examples/zenohc/z_sub_shm.cxx
Labels: enhancement

#244 [Fix] Add missing pragma once
  include/zenoh/api/ext/serialization.hxx
Labels: bug

#246 fix clang format
  examples/universal/z_ping.cxx
  examples/universal/z_put.cxx
  examples/zenohc/z_ping_shm.cxx
Labels: internal

#251 docs clean up
  docs/README.md
  docs/api.rst
  docs/channels.rst
  docs/commons.rst
  docs/interop.rst
  docs/serialization_deserialization.rst
  docs/shared_memory.rst
  examples/simple/Readme.md
  include/zenoh/api/base.hxx
  include/zenoh/api/bytes.hxx
  include/zenoh/api/channels.hxx
  include/zenoh/api/config.hxx
  include/zenoh/api/encoding.hxx
  include/zenoh/api/ext/serialization.hxx
  include/zenoh/api/hello.hxx
  include/zenoh/api/id.hxx
  include/zenoh/api/interop.hxx
  include/zenoh/api/keyexpr.hxx
  include/zenoh/api/liveliness.hxx
  include/zenoh/api/logging.hxx
  include/zenoh/api/publisher.hxx
  include/zenoh/api/query.hxx
  include/zenoh/api/queryable.hxx
  include/zenoh/api/scout.hxx
  include/zenoh/api/session.hxx
  include/zenoh/api/shm/buffer/zshm.hxx
  include/zenoh/api/shm/buffer/zshmmut.hxx
  include/zenoh/api/shm/cleanup.hxx
  include/zenoh/api/shm/provider/alloc_layout.hxx
  include/zenoh/api/shm/provider/types.hxx
  include/zenoh/api/subscriber.hxx
Labels: documentation

#252 clarify library requirements regarding C++17 compiler
  README.md
  include/zenoh.hxx
Labels: documentation, enhancement

#254 typo fix
  examples/CMakeLists.txt
  examples/universal/z_bytes.cxx
Labels: internal

#256 fix clang-fromat runner to ubuntu24.04 and print clang-format version in ci
  .github/workflows/ci.yml
Labels: internal

#259 add serialization format test
  tests/universal/serialization.cxx
Labels: internal

#260 fix package generation
  CMakeLists.txt
  install/CMakeLists.txt
  install/cpack_project_config.cmake
Labels: internal

#264 fix project version for X.Y.Z
  CMakeLists.txt
  install/CMakeLists.txt
Labels: internal

#265 repo name incorrect
  ci/scripts/build.bash
Labels: internal

#266 cpack calls added
  ci/scripts/build.bash
Labels: internal

#267 cpack call added
  ci/scripts/build.bash
Labels: internal

#269 set deb and rpm packages architecture to all/noarch
  install/cpack_project_config.cmake
Labels: internal

#270 added matching status and matching listener support
  examples/getargs.h
  examples/universal/z_pub.cxx
  examples/zenohc/z_pub_shm.cxx
  include/zenoh/api/base.hxx
  include/zenoh/api/publisher.hxx
Labels: enhancement
